GAMongo.Web/Areas/Admin/Controllers/OnlineCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using GAMongo.Web.Areas.Admin.Models.Customers;
using GAMongo.Services.Customers;
using GAMongo.Services.Directory;
using GAMongo.Services.Security;
using GAMongo.Framework.Kendoui;

namespace GAMongo.Web.Areas.Admin.Controllers
{
    public partial class OnlineCustomerController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerService _customerService;
        private readonly IGeoLookupService _geoLookupService;
        private readonly IPermissionService _permissionService;
        #endregion

        #region Constructors

        public OnlineCustomerController(ICustomerService customerService,
            IGeoLookupService geoLookupService,
            IPermissionService permissionService)
        {
            this._customerService = customerService;
            this._geoLookupService = geoLookupService;
            this._permissionService = permissionService;
        }

        #endregion
        
        #region Methods

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public IActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var customers = _customerService.GetOnlineCustomers(DateTime.UtcNow.AddMinutes(-5),
                null, command.Page - 1, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = customers.Select(x => new OnlineCustomerModel
                {
                    Id = x.Id,
                    CustomerInfo = !string.IsNullOrEmpty(x.Username) ? x.Username : "Guest",
                    LastIpAddress = x.LastIpAddress,
                    Location = _geoLookupService.LookupCountryName(x.LastIpAddress),
                    LastActivityDate = x.LastActivityDateUtc
                }),
                Total = customers.TotalCount
            };

            return Json(gridModel);
        }

        #endregion
    }
}

GAMongo.Web/Areas/Admin/Views/OnlineCustomer/List.cshtml
@inject AdminAreaSettings adminAreaSettings
@{
    //page title
    ViewBag.Title = T("Admin.Customers.OnlineCustomers").Text;
}
<antiforgery-token />
<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-users"></i>
                    @T("Admin.Customers.OnlineCustomers")
                </div>
            </div>
            <div class="portlet-body form">
                <div id="onlinecustomers-grid"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#onlinecustomers-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "OnlineCustomer"))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors"
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: @(adminAreaSettings.DefaultGridPageSize),
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                pageSizes: [@(adminAreaSettings.GridPageSizes)]
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: true,
            columns: [{
                field: "Id",
                title: "@T("Admin.Customers.OnlineCustomers.Fields.CustomerInfo")",
                template: '<a class="k-link" href="@Url.Content("~/Admin/Customer/Edit/")#=Id#">#:CustomerInfo#</a>',
                width: 220,
            }, {
                field: "LastIpAddress",
                title: "@T("Admin.Customers.OnlineCustomers.Fields.IPAddress")",
                width: 100,
            }, {
                field: "Location",
                title: "@T("Admin.Customers.OnlineCustomers.Fields.Location")",
                width: 150,
            }, {
                field: "LastActivityDate",
                title: "@T("Admin.Customers.OnlineCustomers.Fields.LastActivityDate")",
                width: 200,
                type: "date",
                format: "{0:G}"
            }, {
                field: "LastVisitedPage",
                title: "@T("Admin.Customers.OnlineCustomers.Fields.LastVisitedPage")",
                width: 400,
            }]
        });
    });
</script>