GAMongo.Web/Areas/Admin/Models/Plugins/MiscPluginModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Plugins
{
    public partial class MiscPluginModel : BaseGrandModel
    {
        public string FriendlyName { get; set; }
        public string ConfigurationUrl { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Models/Plugins/OfficialFeedListModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

using GAMongo.Framework;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Plugins
{
    public partial class OfficialFeedListModel : BaseGrandModel
    {
        public OfficialFeedListModel()
        {
            AvailableVersions = new List<SelectListItem>();
            AvailableCategories = new List<SelectListItem>();
        }
      
        public string SearchName { get; set; }
        public int SearchVersionId { get; set; }
        public string SearchCategoryId { get; set; }
        public IList<SelectListItem> AvailableVersions { get; set; }
        public IList<SelectListItem> AvailableCategories { get; set; }

        #region Nested classes

        public partial class ItemOverview
        {
            public string Url { get; set; }
            public string Name { get; set; }
            public string CategoryName { get; set; }
            public string SupportedVersions { get; set; }
            public string PictureUrl { get; set; }
        }

        #endregion
    }
}

GAMongo.Web/Areas/Admin/Models/Plugins/PluginListModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

using GAMongo.Framework;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Plugins
{
    public partial class PluginListModel : BaseGrandModel
    {
        public PluginListModel()
        {
            AvailableLoadModes = new List<SelectListItem>();
            AvailableGroups = new List<SelectListItem>();
        }
        public int SearchLoadModeId { get; set; }
        public string SearchGroup { get; set; }
        public IList<SelectListItem> AvailableLoadModes { get; set; }
        public IList<SelectListItem> AvailableGroups { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Models/Plugins/PluginModel.cs
using GAMongo.Framework.Mvc.Models;
using FluentValidation.Attributes;
using GAMongo.Web.Areas.Admin.Validators.Plugins;

namespace GAMongo.Web.Areas.Admin.Models.Plugins
{
    [Validator(typeof(PluginValidator))]
    public partial class PluginModel : BaseGrandModel
    {
        public PluginModel()
        {

        }
       
        public string Group { get; set; }     
        public string FriendlyName { get; set; }        
        public string SystemName { get; set; }        
        public string Version { get; set; }       
        public string Author { get; set; }
        public int DisplayOrder { get; set; }
        public string ConfigurationUrl { get; set; }
        public bool Installed { get; set; }
        public bool CanChangeEnabled { get; set; }
        public bool IsEnabled { get; set; }
        public string LogoUrl { get; set; }
    }   
}

GAMongo.Web/Areas/Admin/Controllers/PluginController.cs
using GAMongo.Core;
using GAMongo.Core.Plugins;
using GAMongo.Framework.Controllers;
using GAMongo.Framework.Extensions;
using GAMongo.Framework.Kendoui;
using GAMongo.Services.Events;
using GAMongo.Services.Logging;
using GAMongo.Services.Security;
using GAMongo.Web.Areas.Admin.Extensions;
using GAMongo.Web.Areas.Admin.Models.Plugins;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;

namespace GAMongo.Web.Areas.Admin.Controllers
{
    public partial class PluginController : BaseAdminController
	{
		#region Fields

        private readonly IPluginFinder _pluginFinder;
        private readonly IWebHelper _webHelper;
        private readonly IPermissionService _permissionService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IEventPublisher _eventPublisher;
	    #endregion

		#region Constructors

        public PluginController(IPluginFinder pluginFinder,
            IWebHelper webHelper,
            IPermissionService permissionService, 
            ICustomerActivityService customerActivityService,
            IEventPublisher eventPublisher)
		{
            this._pluginFinder = pluginFinder;
            this._webHelper = webHelper;
            this._permissionService = permissionService;
            this._customerActivityService = customerActivityService;
            this._eventPublisher = eventPublisher;
		}

		#endregion 

        #region Utilities

        [NonAction]
        protected virtual PluginModel PreparePluginModel(PluginDescriptor pluginDescriptor, 
            bool prepareLocales = true, bool prepareStores = true)
        {
            var pluginModel = pluginDescriptor.ToModel(); 
            //logo
            pluginModel.LogoUrl = pluginDescriptor.GetLogoUrl(_webHelper);

            //configuration URLs

            if (pluginDescriptor.Installed)
            {
                //display configuration URL only when a plugin is already installed
                var pluginInstance = pluginDescriptor.Instance();
                pluginModel.ConfigurationUrl = pluginInstance.GetConfigurationPageUrl();
            }
            return pluginModel;
        }

        #endregion

        #region Methods

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var model = new PluginListModel();
            //load modes
            model.AvailableLoadModes = LoadPluginsMode.All.ToSelectList(false).ToList();
            //groups
            model.AvailableGroups.Add(new SelectListItem { Text = "All", Value = "" });
            foreach (var g in _pluginFinder.GetPluginGroups())
                model.AvailableGroups.Add(new SelectListItem { Text = g, Value = g });
            return View(model);
        }

	    [HttpPost]
        public IActionResult ListSelect(DataSourceRequest command, PluginListModel model)
	    {
	        if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
	            return AccessDeniedView();

	        var loadMode = (LoadPluginsMode) model.SearchLoadModeId;
            var pluginDescriptors = _pluginFinder.GetPluginDescriptors(loadMode, "", model.SearchGroup).ToList();
	        var gridModel = new DataSourceResult
            {
                Data = pluginDescriptors.Select(x => PreparePluginModel(x, false, false))
                .OrderBy(x => x.Group)
                .ToList(),
                Total = pluginDescriptors.Count()
            };
	        return Json(gridModel);
	    }

        [HttpPost, ActionName("List")]
        [FormValueRequired(FormValueRequirement.StartsWith, "install-plugin-link-")]
        
        public IActionResult Install(IFormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            try
            {
                //get plugin system name
                string systemName = null;
                foreach (var formValue in form.Keys)
                    if (formValue.StartsWith("install-plugin-link-", StringComparison.OrdinalIgnoreCase))
                        systemName = formValue.Substring("install-plugin-link-".Length);

                var pluginDescriptor = _pluginFinder.GetPluginDescriptorBySystemName(systemName, LoadPluginsMode.All);
                if (pluginDescriptor == null)
                    //No plugin found with the specified id
                    return RedirectToAction("List");

                //check whether plugin is not installed
                if (pluginDescriptor.Installed)
                    return RedirectToAction("List");

                //install plugin
                pluginDescriptor.Instance().Install();
                SuccessNotification("Installed");

                //restart application
                _webHelper.RestartAppDomain();
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
            }
             
            return RedirectToAction("List");
        }

        [HttpPost, ActionName("List")]
        [FormValueRequired(FormValueRequirement.StartsWith, "uninstall-plugin-link-")]        
        public IActionResult Uninstall(IFormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            try
            {
                //get plugin system name
                string systemName = null;
                foreach (var formValue in form.Keys)
                    if (formValue.StartsWith("uninstall-plugin-link-", StringComparison.OrdinalIgnoreCase))
                        systemName = formValue.Substring("uninstall-plugin-link-".Length);

                var pluginDescriptor = _pluginFinder.GetPluginDescriptorBySystemName(systemName, LoadPluginsMode.All);
                if (pluginDescriptor == null)
                    //No plugin found with the specified id
                    return RedirectToAction("List");

                //check whether plugin is installed
                if (!pluginDescriptor.Installed)
                    return RedirectToAction("List");

                //uninstall plugin
                pluginDescriptor.Instance().Uninstall();
                SuccessNotification("Uninstalled");

                //restart application
                _webHelper.RestartAppDomain();
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
            }

            return RedirectToAction("List");
        }

        [HttpPost, ActionName("List")]
        [FormValueRequired(FormValueRequirement.StartsWith, "remove-plugin-link-")]
        public IActionResult Remove(IFormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            try
            {
                //get plugin system name
                string systemName = null;
                foreach (var formValue in form.Keys)
                    if (formValue.StartsWith("remove-plugin-link-", StringComparison.OrdinalIgnoreCase))
                        systemName = formValue.Substring("remove-plugin-link-".Length);

                var pluginDescriptor = _pluginFinder.GetPluginDescriptorBySystemName(systemName, LoadPluginsMode.All);
                if (pluginDescriptor == null)
                    //No plugin found with the specified id
                    return RedirectToAction("List");

                var pluginsPath = CommonHelper.MapPath(PluginManager.PluginsPath);

                foreach (var folder in Directory.GetDirectories(pluginsPath))
                {
                    if (Path.GetFileName(folder) != "bin" && Directory.GetFiles(folder).Select(x => Path.GetFileName(x)).Contains(pluginDescriptor.PluginFileName))
                    {
                        CommonHelper.DeleteDirectory(folder);
                    }
                }

                //uninstall plugin
                SuccessNotification("Removed");

                //restart application
                _webHelper.RestartAppDomain();
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
            }

            return RedirectToAction("List");
        }

        public IActionResult ReloadList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            //restart application
            _webHelper.RestartAppDomain();
            return RedirectToAction("List");
        }


        [HttpPost]
        public IActionResult UploadPlugin(IFormFile zippedFile)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            if (zippedFile == null || zippedFile.Length == 0)
            {
                ErrorNotification("UploadFile");
                return RedirectToAction("List");
            }

            string zipFilePath = "";
            PluginDescriptor descriptor = new PluginDescriptor();
            try
            {
                if (!Path.GetExtension(zippedFile.FileName)?.Equals(".zip", StringComparison.InvariantCultureIgnoreCase) ?? true)
                    throw new Exception("Only zip archives are supported");

                //ensure that temp directory is created
                var tempDirectory = CommonHelper.MapPath("~/App_Data/TempUploads");

GAMongo.Web/Areas/Admin/Views/Plugin/EditPopup.cshtml
@model PluginModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminPopupLayout.cshtml";
    //page title
    ViewBag.Title = T("Admin.Configuration.Plugins.EditDetails").Text;
}

<form asp-controller="Plugin" asp-action="EditPopup" method="post" asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plug"></i>
                        @T("Admin.Configuration.Plugins.EditDetails")
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdatePlugin", Model)
                </div>
            </div>
        </div>
    </div>
</form>

GAMongo.Web/Areas/Admin/Views/Plugin/List.cshtml
@model PluginListModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Plugins.Local").Text;
}
<form asp-controller="Plugin" asp-action="List" method="post" id="plugins-form">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-plug"></i>
                        @T("Admin.Configuration.Plugins.Local")
                    </div>
                    <div class="actions btn-group btn-group-devided">
                        <a href="@Url.Action("ReloadList")" class="btn default">@T("Admin.Configuration.Plugins.ReloadList")</a>
                        <input type="button" id="importfile" class="btn btn-success" value="@T("Admin.Configuration.Plugins.Upload")" />
                    </div>
                </div>
                <div class="portlet-body form">
                    <div class="note note-info">
                        <h4>@T("Admin.Configuration.Plugins.Description"):</h4>
                        <ol>
                            <li>@T("Admin.Configuration.Plugins.Description.Step1")</li>
                            <li>@T("Admin.Configuration.Plugins.Description.Step2")</li>
                            <li>@T("Admin.Configuration.Plugins.Description.Step3")</li>
                            <li>@T("Admin.Configuration.Plugins.Description.Step4")</li>
                            <li>@T("Admin.Configuration.Plugins.Description.Step5")</li>
                        </ol>
                        <p>
                            You can download more grandnode plugins on our <a href="https://www.grandnode.com/extensions?utm_source=admin-panel&utm_medium=plugins&utm_campaign=admin-panel" target="_blank">extensions directory</a>
                        </p>

                    </div>
                    <div class="form-horizontal">
                        <div class="form-body">
                            <div class="form-group">
                                <admin-label asp-for="SearchLoadModeId" />
                                <div class="col-md-4 col-sm-6">
                                    <admin-select asp-for="SearchLoadModeId" asp-items="Model.AvailableLoadModes" />
                                </div>
                            </div>
                            <div class="form-group">
                                <admin-label asp-for="SearchGroup" />
                                <div class="col-md-4 col-sm-6">
                                    <admin-select asp-for="SearchGroup" asp-items="Model.AvailableGroups" />
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9">
                                    <button class="btn btn-success filter-submit" id="search-plugins">
                                        <i class="fa fa-search"></i> @T("Admin.Common.Search")
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id="plugins-grid"></div>
                </div>
            </div>
        </div>
    </div>

    @*import resources form*@

    <script type="text/javascript">
        $(document).ready(function () {

            //import plugin
            $("#importfile").click(function (e) {
                e.preventDefault();
                var window = $("#importfile-window");
                if (!window.data("kendoWindow")) {
                    window.kendoWindow({
                        modal: true,
                        title: "@T("Admin.Configuration.Plugins.Upload")",
                        actions: ["Close"]
                    });
                }
                window.data('kendoWindow').center().open();
            });

            //install a plugin
            $("#plugins-grid").on("click", ".install-plugin-link", function (e) {
                $("html, body").animate({ scrollTop: 0 }, 400);
                showThrobber('@Html.Raw(System.Text.Encodings.Web.JavaScriptEncoder.Default.Encode(T("Admin.Configuration.Plugins.Fields.Install.Progress").Text))');
                return true;
            });

            //uninstall a plugin
            $("#plugins-grid").on("click", ".uninstall-plugin-link", function (e) {
                $("html, body").animate({ scrollTop: 0 }, 400);
                showThrobber('@Html.Raw(System.Text.Encodings.Web.JavaScriptEncoder.Default.Encode(T("Admin.Configuration.Plugins.Fields.Uninstall.Progress").Text))');
                return true;
            });

    });
    </script>

    <script>
        $(document).ready(function() {
            $("#plugins-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("ListSelect", "Plugin"))",
                            type: "POST",
                            dataType: "json",
                            data: additionalData
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [
                    {
                        field: "Group",
                        title: "@T("Admin.Configuration.Plugins.Fields.Group")"
                    }, {
                        field: "LogoUrl",
                        title: "@T("Admin.Configuration.Plugins.Fields.Logo")",
                        width: 100,
                        template: '<img src="#=LogoUrl#" />',
                        headerAttributes: { style: "text-align:center" },
                        attributes: { style: "text-align:center" }
                    }, {
                        field: "FriendlyName",
                        title: "@T("Admin.Configuration.Plugins.Info")",
                        template: '<b>#:FriendlyName#</b>' +
                            '<br />@T("Admin.Configuration.Plugins.Fields.Version"): #:Version#' +
                            '<br />@T("Admin.Configuration.Plugins.Fields.Author"): #:Author#' +
                            '<br />@T("Admin.Configuration.Plugins.Fields.SystemName"): #:SystemName#' +
                            '<br />@T("Admin.Configuration.Plugins.Fields.DisplayOrder"): #:DisplayOrder#' +
                            '<br />@T("Admin.Configuration.Plugins.Fields.Installed"): # if(Installed) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} # ' +
                            '# if(CanChangeEnabled) {# <br />@T("Admin.Configuration.Plugins.Fields.IsEnabled"):  # if(IsEnabled) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} # #} #' +
                            //allow configuration only when a plugin has a configuration URL specified
                            '<br /># if(ConfigurationUrl && ConfigurationUrl.length > 0) {# <a class="btn default" href="#=ConfigurationUrl#">@T("Admin.Configuration.Plugins.Fields.Configure")</a>&nbsp;&nbsp;&nbsp; #} #' +
                            '<a class="btn default" href="javascript:OpenWindow(\'@Url.Content("~/Admin/Plugin/EditPopup")?systemName=#=SystemName#&btnId=btnRefresh&formId=plugins-form\', 800, 500, true);">@T("Admin.Common.Edit")</a>',
                    }, {
                        field: "Installed",
                        title: "@T("Admin.Configuration.Plugins.Fields.Installation")",
                        template: '# if(Installed) {# <input type="submit" name="uninstall-plugin-link-#=SystemName#" class="btn red uninstall-plugin-link" value="@T("Admin.Configuration.Plugins.Fields.Uninstall")" /> #} else {#  <input type="submit" name="install-plugin-link-#=SystemName#" class="btn green install-plugin-link" value="@T("Admin.Configuration.Plugins.Fields.Install")" /> <input type="submit" name="remove-plugin-link-#=SystemName#" class="btn" value="@T("Admin.Configuration.Plugins.Fields.Remove")" />#} #',
                        headerAttributes: {style: "text-align:center" },
                        attributes: { style: "text-align:center" }
                    }
                ]
            });
        });
    </script>
    <input type="submit" id="btnRefresh" style="display: none" />
    <script type="text/javascript">
        $(document).ready(function () {
            //search button
            $('#search-plugins').click(function () {
                //search
                var grid = $('#plugins-grid').data('kendoGrid');
                grid.dataSource.read();

                return false;
            });

            $('#btnRefresh').click(function () {
                //refresh grid
                var grid = $("#plugins-grid").data('kendoGrid');
                grid.dataSource.read();

                //return false to don't reload a page
                return false;
            });
        });
        function additionalData() {
            var data = {
                SearchLoadModeId: $('#SearchLoadModeId').val(),
                SearchGroup: $('#SearchGroup').val()
            };
            addAntiForgeryToken(data);
            return data;
        }
    </script>
</form>

<div class="modal-dialog" id="importfile-window" style="display:none; padding: 0 10px;">
    <form asp-controller="Plugin" asp-action="UploadPlugin" method="post" enctype = "multipart/form-data">
        <antiforgery-token />
        <ul class="common-list">
            <li>
                <strong>NOTE: It can take up to several minutes.</strong>
            </li>
            <li>
                <strong>NOTE: DO NOT click twice.</strong>
            </li>
        </ul>
        <div class="form-group">
            <div class="col-md-2" style="margin-top: 7px; height: 34px; padding-left: 25px;">
                <label class="control-label">
                    Zip file
                </label>
            </div>
            <div class="col-md-10">
                <input id="importfiledialog" name="zippedFile" class="form-control" type="file">
            </div>
        </div>
        <div class="form-group">
            &nbsp;
        </div>
            <div class="form-group">
                <div class="col-md-2">
                    &nbsp;
                </div>
                <div class="col-md-10 text-right mt-10">
                    <input id="importfilesubmit" class="btn blue" value="@T("Admin.Configuration.Plugins.Upload")" type="submit">
                </div>
            </div>
    </form>
</div>

GAMongo.Web/Areas/Admin/Views/Plugin/_CreateOrUpdatePlugin.TabInfo.cshtml
@model PluginModel
   
@(Html.LocalizedEditor<PluginModel, PluginLocalizedModel>("plugin-localized",
    @<div class="form-horizontal">
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="@Model.Locales[item].FriendlyName" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="@Model.Locales[item].FriendlyName" />
                    <span asp-validation-for="@Model.Locales[item].FriendlyName"></span>
                </div>
            </div>
            <input asp-for="@Model.Locales[item].LanguageId" type="hidden" />
        </div>
    </div>
        ,
    @<div class="form-horizontal">
        <div class="form-body">
            <div class="form-group">
                <admin-label asp-for="FriendlyName" />
                <div class="col-md-9 col-sm-9">
                    <admin-input asp-for="FriendlyName" />
                    <span asp-validation-for="FriendlyName"></span>
                </div>
            </div>
        </div>
    </div>
))
<div class="form-horizontal">
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="DisplayOrder" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="DisplayOrder" />
                <span asp-validation-for="DisplayOrder"></span>
            </div>
        </div>
        @if (Model.CanChangeEnabled)
            {
            <div class="form-group">
                <admin-label asp-for="IsEnabled" />
                <div class="col-md-9 col-sm-9">
                    <label class="mt-checkbox mt-checkbox-outline">
                        <admin-input asp-for="IsEnabled" />
                        <span></span>
                    </label>
                    <span asp-validation-for="IsEnabled"></span>
                </div>
            </div>
        }
    </div>
</div>

GAMongo.Web/Areas/Admin/Views/Plugin/_CreateOrUpdatePlugin.cshtml
@model PluginModel
@inject IEventPublisher eventPublisher
<div asp-validation-summary="All"></div>
<input asp-for="SystemName" type="hidden" />
@if (ViewBag.RefreshPage == true)
{
    <script type="text/javascript">
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
<script>
    $(document).ready(function () {
        $("#plugin-edit").kendoTabStrip({
            animation: {
                open: {
                    effects: "fadeIn"
                }
            },
            select: tabstrip_on_tab_select
        });
    });
</script>
<div id="plugin-edit">
    <ul>
        <li @Html.RenderSelectedTabIndex(0, GetSelectedTabIndex())>
            @T("Admin.Configuration.Plugins.Info")
        </li>
        <li @Html.RenderSelectedTabIndex(1, GetSelectedTabIndex())>
            @T("Admin.Configuration.Plugins.Stores")
        </li>
    </ul>
    <div>
        @Html.Partial("_CreateOrUpdatePlugin.TabInfo.cshtml", @Model)
    </div>
    <div>
        @Html.Partial("_CreateOrUpdatePlugin.TabStores.cshtml", Model)
    </div>
</div>
@{
    //custom tabs
    var eventMessage = new AdminTabStripCreated(this.Html, "plugin-edit");
    eventPublisher.Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}