GAMongo.Web/Areas/Admin/Models/Customers/CustomerListModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using System.Collections.Generic;
using GAMongo.Framework;
using GAMongo.Framework.Mvc;
using System.ComponentModel.DataAnnotations;

namespace GAMongo.Web.Areas.Admin.Models.Customers
{
    public partial class CustomerListModel : BaseGrandModel
    {
        public CustomerListModel()
        {
            SearchCustomerRoleIds = new List<string>();
            AvailableCustomerRoles = new List<SelectListItem>();
        }       
        public IList<SelectListItem> AvailableCustomerRoles { get; set; }

        [UIHint("MultiSelect")]
        public IList<string> SearchCustomerRoleIds { get; set; }
        public string SearchUsername { get; set; }

    }
}

GAMongo.Web/Areas/Admin/Models/Customers/CustomerModel.cs
using GAMongo.Framework.Mvc.Models;
using GAMongo.Framework.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FluentValidation.Attributes;
using GAMongo.Web.Areas.Admin.Validators.Customers;

namespace GAMongo.Web.Areas.Admin.Models.Customers
{
    [Validator(typeof(CustomerValidator))]
    public partial class CustomerModel : BaseGrandEntityModel
    {
        public CustomerModel()
        {
            this.AvailableCustomerRoles = new List<CustomerRoleModel>();
        }

        public bool AllowUsersToChangeUsernames { get; set; }
        public bool UsernamesEnabled { get; set; }       
        public string Username { get; set; }
       
        [DataType(DataType.Password)]
        [NoTrim]
        public string Password { get; set; }       
        public bool Active { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime LastActivityDate { get; set; }
        public string LastIpAddress { get; set; }
        public string LastVisitedPage { get; set; }
        public string LastUrlReferrer { get; set; }
        public string CustomerRoleNames { get; set; }
        public List<CustomerRoleModel> AvailableCustomerRoles { get; set; }
        public string[] SelectedCustomerRoleIds { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Models/Customers/CustomerRoleModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

using FluentValidation.Attributes;
using GAMongo.Web.Areas.Admin.Validators.Customers;
using GAMongo.Framework;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Customers
{
    [Validator(typeof(CustomerRoleValidator))]
    public partial class CustomerRoleModel : BaseGrandEntityModel
    {      
        public string Name { get; set; }
        public bool Active { get; set; }       
        public bool IsSystemRole { get; set; }
        public string SystemName { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Models/Customers/OnlineCustomerModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using System;
using GAMongo.Framework;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Customers
{
    public partial class OnlineCustomerModel : BaseGrandEntityModel
    {
        public string CustomerInfo { get; set; }
        public string LastIpAddress { get; set; }
        public string Location { get; set; }
        public DateTime LastActivityDate { get; set; }        
        public string LastVisitedPage { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Models/Customers/RegisteredCustomerReportLineModel.cs
using GAMongo.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using GAMongo.Framework.Mvc.ModelBinding;
using GAMongo.Framework;
using GAMongo.Framework.Mvc;

namespace GAMongo.Web.Areas.Admin.Models.Customers
{
    public partial class RegisteredCustomerReportLineModel : BaseGrandModel
    {
        public string Period { get; set; }
        public int Customers { get; set; }
    }
}

GAMongo.Web/Models/Customer/AccountActivationModel.cs
using GAMongo.Framework.Mvc.Models;

namespace GAMongo.Web.Models.Customer
{
    public partial class AccountActivationModel : BaseGrandModel
    {
        public string Result { get; set; }
    }
}

GAMongo.Web/Models/Customer/ChangePasswordModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using FluentValidation.Attributes;
using GAMongo.Framework;
using GAMongo.Framework.Mvc.Models;
using GAMongo.Web.Validators.Customer;
using GAMongo.Framework.Mvc.ModelBinding;

namespace GAMongo.Web.Models.Customer
{
    [Validator(typeof(ChangePasswordValidator))]
    public partial class ChangePasswordModel : BaseGrandModel
    {
        [NoTrim]
        [DataType(DataType.Password)]
        [GrandResourceDisplayName("Account.ChangePassword.Fields.OldPassword")]
        public string OldPassword { get; set; }

        [NoTrim]
        [DataType(DataType.Password)]
        [GrandResourceDisplayName("Account.ChangePassword.Fields.NewPassword")]
        public string NewPassword { get; set; }

        [NoTrim]
        [DataType(DataType.Password)]
        [GrandResourceDisplayName("Account.ChangePassword.Fields.ConfirmNewPassword")]
        public string ConfirmNewPassword { get; set; }

        public string Result { get; set; }

    }
}

GAMongo.Web/Models/Customer/CustomerNavigationModel.cs
using GAMongo.Framework.Mvc.Models;

namespace GAMongo.Web.Models.Customer
{
    public partial class CustomerNavigationModel : BaseGrandModel
    {
        public bool HideInfo { get; set; }
        public bool HideAddresses { get; set; }
        public bool HideOrders { get; set; }
        public bool HideBackInStockSubscriptions { get; set; }
        public bool HideReturnRequests { get; set; }
        public bool HideDownloadableProducts { get; set; }
        public bool HideRewardPoints { get; set; }
        public bool HideChangePassword { get; set; }
        public bool HideDeleteAccount { get; set; }
        public bool HideAvatar { get; set; }
        public bool HideAuctions { get; set; }
        public bool HideForumSubscriptions { get; set; }
        public bool ShowVendorInfo { get; set; }

        public CustomerNavigationEnum SelectedTab { get; set; }
    }

    public enum CustomerNavigationEnum
    {
        Info = 0,
        Addresses = 10,
        Orders = 20,
        BackInStockSubscriptions = 30,
        ReturnRequests = 40,
        DownloadableProducts = 50,
        RewardPoints = 60,
        ChangePassword = 70,
        DeleteAccount = 75,
        Avatar = 80,
        ForumSubscriptions = 90,
        VendorInfo = 100,
        Auctions = 110
    }
}

GAMongo.Web/Models/Customer/DeleteAccountModel.cs
using System.ComponentModel.DataAnnotations;
using FluentValidation.Attributes;
using GAMongo.Framework.Mvc.Models;
using GAMongo.Web.Validators.Customer;
using GAMongo.Framework.Mvc.ModelBinding;

namespace GAMongo.Web.Models.Customer
{
    [Validator(typeof(DeleteAccountValidator))]
    public partial class DeleteAccountModel : BaseGrandModel
    {
        [NoTrim]
        [DataType(DataType.Password)]
        [GrandResourceDisplayName("Account.DeleteAccount.Fields.Password")]
        public string Password { get; set; }

    }
}

GAMongo.Web/Models/Customer/ExternalAuthenticationMethodModel.cs
using GAMongo.Framework.Mvc.Models;

namespace GAMongo.Web.Models.Customer
{
    public partial class ExternalAuthenticationMethodModel : BaseGrandModel
    {
        public string ViewComponentName { get; set; }
    }
}

GAMongo.Web/Models/Customer/RegisterResultModel.cs
using GAMongo.Framework.Mvc.Models;

namespace GAMongo.Web.Models.Customer
{
    public partial class RegisterResultModel : BaseGrandModel
    {
        public string Result { get; set; }
    }
}

GAMongo.Web/Areas/Admin/Controllers/CustomerController.cs
using GAMongo.Core;
using GAMongo.Core.Domain.Customers;
using GAMongo.Core.Domain.Orders;
using GAMongo.Core.Infrastructure;
using GAMongo.Framework.Controllers;
using GAMongo.Framework.Extensions;
using GAMongo.Framework.Kendoui;
using GAMongo.Framework.Mvc;
using GAMongo.Framework.Mvc.Filters;
using GAMongo.Services.Customers;
using GAMongo.Services.Directory;
using GAMongo.Services.Logging;
using GAMongo.Services.Orders;
using GAMongo.Services.Security;
using GAMongo.Web.Areas.Admin.Models.Common;
using GAMongo.Web.Areas.Admin.Models.Customers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;

namespace GAMongo.Web.Areas.Admin.Controllers
{
    public partial class CustomerController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerService _customerService;
        private readonly IWorkContext _workContext;
        private readonly IOrderService _orderService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        #endregion

        #region Constructors

        public CustomerController(ICustomerService customerService,
            IWorkContext workContext,
            IOrderService orderService,
            ICustomerActivityService customerActivityService,
            IPermissionService permissionService)
        {
            this._customerService = customerService;
            this._workContext = workContext;
            this._orderService = orderService;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;           
        }

        #endregion

        #region Utilities

        [NonAction]
        protected virtual string[] ParseCustomerTags(string customerTags)
        {
            var result = new List<string>();
            if (!String.IsNullOrWhiteSpace(customerTags))
            {
                string[] values = customerTags.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                foreach (string val1 in values)
                    if (!String.IsNullOrEmpty(val1.Trim()))
                        result.Add(val1.Trim());
            }
            return result.ToArray();
        }

        [NonAction]
        protected virtual void SaveCustomerTags(Customer customer, string[] customerTags)
        {
            if (customer == null)
                throw new ArgumentNullException("customer");

            //product tags
            var existingCustomerTags = customer.CustomerTags.ToList();                      
        }



        [NonAction]
        protected virtual string GetCustomerRolesNames(IList<CustomerRole> customerRoles, string separator = ",")
        {
            var sb = new StringBuilder();
            for (int i = 0; i < customerRoles.Count; i++)
            {
                sb.Append(customerRoles[i].Name);
                if (i != customerRoles.Count - 1)
                {
                    sb.Append(separator);
                    sb.Append(" ");
                }
            }
            return sb.ToString();
        }

      
        [NonAction]
        protected virtual CustomerModel PrepareCustomerModel(Customer customer)
        {
            return new CustomerModel
            {
                Id = customer.Id,
                Username = customer.Username,
                CustomerRoleNames = GetCustomerRolesNames(customer.CustomerRoles.ToList()),
                Active = customer.Active,
                CreatedOn = customer.CreatedOnUtc,
                LastActivityDate = customer.LastActivityDateUtc,
            };
        }   


        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var model = new CustomerListModel
            {
                AvailableCustomerRoles = _customerService.GetAllCustomerRoles(true).Select(cr => new SelectListItem() { Text = cr.Name, Value = cr.Id.ToString(), Selected = (cr.Id == _customerService.GetCustomerRoleBySystemName(SystemCustomerRoleNames.Registered).Id) }).ToList(),
                SearchCustomerRoleIds = new List<string> { _customerService.GetAllCustomerRoles(true).FirstOrDefault(x => x.Id == _customerService.GetCustomerRoleBySystemName(SystemCustomerRoleNames.Registered).Id).Id },
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult CustomerList(DataSourceRequest command, CustomerListModel model,
            string[] searchCustomerRoleIds, string[] searchCustomerTagIds)
        {
            //we use own own binder for searchCustomerRoleIds property 
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var customers = _customerService.GetAllCustomers(
                //customerRoleIds: searchCustomerRoleIds,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize);

            var gridModel = new DataSourceResult
            {
                Data = customers.Select(PrepareCustomerModel),
                Total = customers.TotalCount
            };

            return Json(gridModel);
        }

        public IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var model = new CustomerModel();

            //default value
            model.Active = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]

        public IActionResult Create(CustomerModel model, bool continueEditing, IFormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            if (!String.IsNullOrWhiteSpace(model.Username))
            {
                var cust2 = _customerService.GetCustomerByUsername(model.Username);
                if (cust2 != null)
                    ModelState.AddModelError("", "Username is already registered");
            }

            //validate customer roles
            var allCustomerRoles = _customerService.GetAllCustomerRoles(true);
            var newCustomerRoles = new List<CustomerRole>();
            foreach (var customerRole in allCustomerRoles)
                if (model.SelectedCustomerRoleIds != null && model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                    newCustomerRoles.Add(customerRole);
            
            if (ModelState.IsValid)
            {
                var customer = new Customer
                {
                    CustomerGuid = Guid.NewGuid(),
                    Username = model.Username,
                    Active = model.Active,
                    CreatedOnUtc = DateTime.UtcNow,
                    LastActivityDateUtc = DateTime.UtcNow,
                };
                _customerService.InsertCustomer(customer);
                                
                //customer roles
                foreach (var customerRole in newCustomerRoles)
                {
                    //ensure that the current customer cannot add to "Administrators" system role if he's not an admin himself
                    if (customerRole.SystemName == SystemCustomerRoleNames.Administrators &&
                        !_workContext.CurrentCustomer.IsAdmin())
                        continue;

                    customer.CustomerRoles.Add(customerRole);
                    customerRole.CustomerId = customer.Id;
                    //_customerService.InsertCustomerRoleInCustomer(customerRole);
                }

                SuccessNotification("Added");
                return continueEditing ? RedirectToAction("Edit", new { id = customer.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            //PrepareCustomerModel(model.ToEntity());
            return View(model);

        }

        public IActionResult Edit(string id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var customer = _customerService.GetCustomerById(id);
            if (customer == null || customer.Deleted)
                //No customer found with the specified id
                return RedirectToAction("List");
            var model = PrepareCustomerModel(customer);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public IActionResult Edit(CustomerModel model, bool continueEditing, IFormCollection form)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();

            var customer = _customerService.GetCustomerById(model.Id);
            if (customer == null || customer.Deleted)
                //No customer found with the specified id
                return RedirectToAction("List");

            //validate customer roles
            var allCustomerRoles = _customerService.GetAllCustomerRoles(true);
            var newCustomerRoles = new List<CustomerRole>();
            foreach (var customerRole in allCustomerRoles)
                if (model.SelectedCustomerRoleIds != null && model.SelectedCustomerRoleIds.Contains(customerRole.Id))

GAMongo.Web/Areas/Admin/Views/Customer/Create.cshtml
@model CustomerModel
@{
    //page title
    ViewBag.Title = T("Admin.Customers.Customers.AddNew").Text;
}
<form asp-controller="Customer" asp-action="Create" method="post">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>
                            @T("Admin.Customers.Customers.AddNew") 
                            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Customers.Customers.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>
</form>

GAMongo.Web/Areas/Admin/Views/Customer/Edit.cshtml
@model CustomerModel
@{
    //page title
    ViewBag.Title = T("Admin.Customers.Customers.EditCustomerDetails").Text;
}
<form asp-controller="Customer" asp-action="Edit" method="post" id = "customer-form">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>
                        @T("Admin.Customers.Customers.EditCustomerDetails") - @Model.LastName @Model.FirstName
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Customers.Customers.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided util-btn-margin-bottom-5">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                            <input type="button" id="sendemail" class="btn yellow" value="@T("Admin.Customers.Customers.SendEmail")" />
                            <input type="button" id="sendprivatemessage" class="btn blue" value="@T("Admin.Customers.Customers.SendPM")" />
                            @if (Model.AllowSendingOfWelcomeMessage)
                            {
                                <input type="submit" name="send-welcome-message" class="btn default" value="@T("Admin.Customers.Customers.SendWelcomeMessage")" onclick="return confirm('@T("Admin.Common.AreYouSure")');" />
                            }
                            @if (Model.AllowReSendingOfActivationMessage)
                            {
                                <input type="submit" name="resend-activation-message" class="btn default" value="@T("Admin.Customers.Customers.ReSendActivationMessage")" onclick="return confirm('@T("Admin.Common.AreYouSure")');" />
                            }
                            <span id="customer-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>
</form>
@Html.DeleteConfirmation("customer-delete")

@*send email form*@
<div id="sendemail-window" style="display:none;">
    <form asp-controller="Customer" asp-action="SendEmail" method="post" asp-route-id="Id">
        <antiforgery-token />
        <input type="hidden" asp-for="Id" />
        <div class="form-horizontal">
            <div class="form-body">
                <div class="form-group">
                    <admin-label asp-for="SendEmail.Subject" />
                    <div class="col-md-9 col-sm-9">
                        <admin-input asp-for="SendEmail.Subject" />
                        <span asp-validation-for="SendEmail.Subject"></span>
                    </div>
                </div>
                <div class="form-group">
                    <admin-label asp-for="SendEmail.Body" />
                    <div class="col-md-9 col-sm-9">
                        <admin-textarea asp-for="SendEmail.Body"></admin-textarea>
                        <span asp-validation-for="SendEmail.Body"></span>
                    </div>
                </div>
                <div class="form-group">
                    <admin-label asp-for="SendEmail.SendImmediately" />
                    <div class="col-md-9 col-sm-9">
                        <admin-input asp-for="SendEmail.SendImmediately" />
                        <span asp-validation-for="SendEmail.SendImmediately"></span>
                    </div>
                </div>
                <div class="form-group" id="pnl-send-date">
                    <admin-label asp-for="SendEmail.DontSendBeforeDate" />
                    <div class="col-md-9 col-sm-9">
                        <admin-input asp-for="SendEmail.DontSendBeforeDate" />
                        <span asp-validation-for="SendEmail.DontSendBeforeDate"></span>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="col-md-offset-3 col-sm-offset-3 col-md-6 col-sm-6">
                    <input type="submit" class="btn default" value="@T("Admin.Customers.Customers.SendEmail")" />
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#sendemail").click(function (e) {
            e.preventDefault();
            var window = $("#sendemail-window");
            if (!window.data("kendoWindow")) {
                window.kendoWindow({
                    modal: true,
                    width: "650px",
                    title: "@T("Admin.Customers.Customers.SendEmail")",
                    actions: ["Close"]
                });
            }
            window.data('kendoWindow').center().open();
        });
    });
</script>


@*send PM form*@
<div id="sendprivatemessage-window" style="display:none;">
    <form asp-controller="Customer" asp-action="SendPm" method="post" asp-route-id="Id" >
        <antiforgery-token />
        <input type="hidden" asp-for="Id" />
        <div class="form-horizontal">
            <div class="form-body">
                <div class="form-group">
                    <admin-label asp-for="SendPm.Subject" class="control-label col-md-4 col-sm-4"/>
                    <div class="col-md-8 col-sm-8">
                        <admin-input asp-for="SendPm.Subject" />
                        <span asp-validation-for="SendPm.Subject"></span>
                    </div>
                </div>
                <div class="form-group">
                    <admin-label asp-for="SendPm.Message" class="control-label col-md-4 col-sm-4" />
                    <div class="col-md-8 col-sm-8">
                        <admin-textarea asp-for="SendPm.Message"></admin-textarea>
                        <span asp-validation-for="SendPm.Message"></span>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="col-md-offset-3 col-sm-offset-3 col-md-6 col-sm-6">
                    <input type="submit" class="btn default" value="@T("Admin.Customers.Customers.SendPM")" />
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#sendprivatemessage").click(function (e) {
            e.preventDefault();
            var window = $("#sendprivatemessage-window");
            if (!window.data("kendoWindow")) {
                window.kendoWindow({
                    modal: true,
                    width: "500px",
                    title: "@T("Admin.Customers.Customers.SendPM")",
                    actions: ["Close"]
                });
            }
            window.data('kendoWindow').center().open();
        });
        $("#@Html.FieldIdFor(model => model.SendEmail.SendImmediately)").click(sendImmediately);
        sendImmediately();
    });

    function sendImmediately() {
        if ($('#@Html.FieldIdFor(model => model.SendEmail.SendImmediately)').is(':checked'))
            $('#pnl-send-date').hide();
        else
            $('#pnl-send-date').show();
    }
</script>