GAMongo.Web/Areas/Admin/Controllers/CustomerRoleController.cs
using System;
using System.Linq;
using GAMongo.Web.Areas.Admin.Models.Customers;
using GAMongo.Core;
using GAMongo.Core.Domain.Customers;
using GAMongo.Services.Customers;
using GAMongo.Services.Logging;
using GAMongo.Services.Security;
using GAMongo.Framework.Kendoui;
using Microsoft.AspNetCore.Mvc;
using GAMongo.Web.Areas.Admin.Extensions;
using GAMongo.Framework.Mvc.Filters;

namespace GAMongo.Web.Areas.Admin.Controllers
{
    public partial class CustomerRoleController : BaseAdminController
	{
		#region Fields

		private readonly ICustomerService _customerService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        private readonly IWorkContext _workContext;

		#endregion

		#region Constructors

        public CustomerRoleController(ICustomerService customerService,
            ICustomerActivityService customerActivityService,
            IPermissionService permissionService,
            IWorkContext workContext)
		{
            this._customerService = customerService;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;
            this._workContext = workContext;
		}

		#endregion 

        #region Utilities

        [NonAction]
        protected CustomerRoleModel PrepareCustomerRoleModel(CustomerRole customerRole)
        {
            var model = customerRole.ToModel();
            return model;
        }

        #endregion

        #region Customer roles

        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

		public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
			return View();
		}

		[HttpPost]
		public IActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            var customerRoles = _customerService.GetAllCustomerRoles(true);
            var gridModel = new DataSourceResult
			{
                Data = customerRoles.Select(PrepareCustomerRoleModel),
                Total = customerRoles.Count()
			};
            return Json(gridModel);
        }

        public IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            var model = new CustomerRoleModel();
            //default values
            model.Active = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public IActionResult Create(CustomerRoleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            if (ModelState.IsValid)
            {
                var customerRole = model.ToEntity();
                _customerService.InsertCustomerRole(customerRole);

                //activity log
                _customerActivityService.InsertActivity("AddNewCustomerRole", customerRole.Id, "AddNewCustomerRole", customerRole.Name);

                SuccessNotification("Added");
                return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

		public IActionResult Edit(string id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            var customerRole = _customerService.GetCustomerRoleById(id);
            if (customerRole == null)
                //No customer role found with the specified id
                return RedirectToAction("List");
		    
            var model = PrepareCustomerRoleModel(customerRole);
            return View(model);
		}

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public IActionResult Edit(CustomerRoleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            var customerRole = _customerService.GetCustomerRoleById(model.Id);
            if (customerRole == null)
                //No customer role found with the specified id
                return RedirectToAction("List");

            try
            {
                if (ModelState.IsValid)
                {
                    if (customerRole.IsSystemRole && !model.Active)
                        throw new GrandException("CantEditSystem");

                    if (customerRole.IsSystemRole && !customerRole.SystemName.Equals(model.SystemName, StringComparison.OrdinalIgnoreCase))
                        throw new GrandException("CantEditSystem");
                    
                    customerRole = model.ToEntity(customerRole);
                    _customerService.UpdateCustomerRole(customerRole);

                    //activity log
                    _customerActivityService.InsertActivity("EditCustomerRole", customerRole.Id, "EditCustomerRole", customerRole.Name);

                    SuccessNotification("Updated");
                    return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id}) : RedirectToAction("List");
                }

                //If we got this far, something failed, redisplay form
                return View(model);
            }
            catch (Exception exc)
            {
                ErrorNotification(exc);
                return RedirectToAction("Edit", new { id = customerRole.Id });
            }
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel))
                return AccessDeniedView();
            
            var customerRole = _customerService.GetCustomerRoleById(id);
            if (customerRole == null)
                //No customer role found with the specified id
                return RedirectToAction("List");

            try
            {
                //activity log
                _customerActivityService.InsertActivity("DeleteCustomerRole", customerRole.Id, "DeleteCustomerRole", customerRole.Name);

                _customerService.DeleteCustomerRole(customerRole);

                SuccessNotification("Deleted");
                return RedirectToAction("List");
            }
            catch (Exception exc)
            {
                ErrorNotification(exc.Message);
                return RedirectToAction("Edit", new { id = customerRole.Id });
            }

		}

        #endregion
    }
}

GAMongo.Web/Areas/Admin/Views/CustomerRole/Create.cshtml
@model CustomerRoleModel
@{
    //page title
    ViewBag.Title = T("Admin.Customers.CustomerRoles.AddNew").Text;
}
<form asp-controller="CustomerRole" asp-action="Create" method="post" id="customerrole-form">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-users"></i>
                        @T("Admin.Customers.CustomerRoles.AddNew")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Customers.CustomerRoles.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>
</form>

GAMongo.Web/Areas/Admin/Views/CustomerRole/Edit.cshtml
@model CustomerRoleModel
@{
    //page title
    ViewBag.Title = T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails").Text;
}
<form asp-controller="CustomerRole" asp-action="Edit" method="post" id="customerrole-form">
    <antiforgery-token />
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-users"></i>
                        @T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails") - @Model.Name
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Customers.CustomerRoles.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions util-btn-margin-bottom-5">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        <span id="customerrole-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>
</form>
@Html.DeleteConfirmation("customerrole-delete")

GAMongo.Web/Areas/Admin/Views/CustomerRole/List.cshtml
@{
    //page title
    ViewBag.Title = "CustomerRoles";
}
<antiforgery-token />
<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-users"></i>
                    CustomerRoles
                </div>
                <div class="actions">
                    <a href="@Url.Action("Create")" class="btn green"><i class="fa fa-plus"></i><span class="hidden-xs">AddNew</span></a>
                </div>
            </div>
            <div class="portlet-body form">
                <div id="customerroles-grid"></div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#customerroles-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "CustomerRole"))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors"
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: true,
            columns: [{
                field: "Name",
                title: "@T("Admin.Customers.CustomerRoles.Fields.Name")",
                width: 300,
                template: '<a class="k-link" href="Edit/#=Id#">#=Name#</a>'
            }, {
                field: "FreeShipping",
                title: "@T("Admin.Customers.CustomerRoles.Fields.FreeShipping")",
                width: 100,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(FreeShipping) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            }, {
                field: "TaxExempt",
                title: "@T("Admin.Customers.CustomerRoles.Fields.TaxExempt")",
                width: 80,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(TaxExempt) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            },{
                field: "Active",
                title: "@T("Admin.Customers.CustomerRoles.Fields.Active")",
                width: 80,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(Active) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            },{
                field: "IsSystemRole",
                title: "@T("Admin.Customers.CustomerRoles.Fields.IsSystemRole")",
                width: 80,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(IsSystemRole) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            },{
                field: "PurchasedWithProductName",
                title: "@T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct")",
                width: 100,
                minScreenWidth: 750,
            }]
        });
    });
</script>
        

GAMongo.Web/Areas/Admin/Views/CustomerRole/_CreateOrUpdate.TabInfo.cshtml
@model CustomerRoleModel
<div class="form-horizontal">
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="Name" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="SystemName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SystemName" />
                <span asp-validation-for="SystemName"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="FreeShipping" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline">
                    <admin-input asp-for="FreeShipping" />
                    <span></span>
                </label>
                <span asp-validation-for="FreeShipping"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="TaxExempt" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline">
                    <admin-input asp-for="TaxExempt" />
                    <span></span>
                </label>
                <span asp-validation-for="TaxExempt"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Active" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline">
                    <admin-input asp-for="Active" />
                    <span></span>
                </label>
                <span asp-validation-for="Active"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="EnablePasswordLifetime" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline">
                    <admin-input asp-for="EnablePasswordLifetime" />
                    <span></span>
                </label>
                <span asp-validation-for="EnablePasswordLifetime"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="IsSystemRole" />
            <div class="col-md-9 col-sm-9">
                <label class="control-label"> @Model.IsSystemRole.ToString()</label>
                <input asp-for="IsSystemRole" type="hidden" />
                <span asp-validation-for="IsSystemRole"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="PurchasedWithProductId" />
            <div class="col-md-9 col-sm-9">
                <input asp-for="PurchasedWithProductId" type="hidden" />
                <span id="purchased-with-product-name">@Model.PurchasedWithProductName</span>
                <span asp-validation-for="PurchasedWithProductId"></span>
                <input type="submit" value=@T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose") onclick="javascript:OpenWindow('@(Url.Action("AssociateProductToCustomerRolePopup", "CustomerRole", new { productIdInput = Html.FieldIdFor(model => model.PurchasedWithProductId), productNameInput = "purchased-with-product-name", btnId = "btnRefreshPurchasedWithProduct" }))', 800, 800, true); return false;" class="btn default" />
                <input type="submit" id="purchased-with-product-name-remove" value=@T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Remove") class="btn default" />
                <input type="submit" id="btnRefreshPurchasedWithProduct" style="display: none" />
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('#purchased-with-product-name-remove').click(function () {
                            $('#purchased-with-product-name').text('');
                            $("#@Html.FieldIdFor(model => model.PurchasedWithProductId)").val(0);
                            toggleRemoveButton();
                            //return false to don't reload a page
                            return false;
                        });

                        $('#btnRefreshPurchasedWithProduct').click(function () {
                            toggleRemoveButton();

                            //return false to don't reload a page
                            return false;
                        });
                    });
                </script>

            </div>
        </div>
    </div>
</div>

GAMongo.Web/Areas/Admin/Views/CustomerRole/_CreateOrUpdate.cshtml
@model CustomerRoleModel
@inject IEventPublisher eventPublisher
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<script type="text/javascript">
    $(document).ready(function () {
        toggleRemoveButton();

        $("#customerrole-edit").kendoTabStrip({
            animation: {
                open: {
                    effects: "fadeIn"
                }
            },
            select: tabstrip_on_tab_select
        });
    });
    function toggleRemoveButton() {
        if ($('#@Html.FieldIdFor(model => model.PurchasedWithProductId)').val() > 0) {
            $('#purchased-with-product-name-remove').show();
        }
        else {
            $('#purchased-with-product-name-remove').hide();
        }
    }
</script>

<div id="customerrole-edit">
    <ul>
        <li @Html.RenderSelectedTabIndex(0, GetSelectedTabIndex())>
            @T("Admin.Customers.CustomerRoles.Info")
        </li>
        <li @Html.RenderSelectedTabIndex(1, GetSelectedTabIndex())>
            @T("Admin.Customers.CustomerRoles.Products")
        </li>
    </ul>
    <div>
        @Html.Partial("_CreateOrUpdate.TabInfo", Model)
    </div>
    <div>
        @Html.Partial("_CreateOrUpdate.TabProducts", Model)
    </div>
</div>
@{
    //custom tabs
    var eventMessage = new AdminTabStripCreated(this.Html, "customerrole-edit");
    eventPublisher.Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}
@*save selected tab index*@
<input type="hidden" id="selected-tab-index" name="selected-tab-index" value="@(GetSelectedTabIndex())">